POST http://localhost:8080/auth/signin
Content-Type: application/json

{
  "username": "admin1",
  "password": "admin1"
}




GET       http://localhost:8080/comments/1

###
POST        http://localhost:8080/comments/


### Add a Comment
POST http://localhost:8080/comments
Content-Type: application/json
Authorization: 2d3f88e56a3935b2ec6dfa44cd279608

{
    "comment": "This is a sample comment.",
    "TopicId": 35,
    "useriD": 1
}
