POST       http://localhost:8080/topics/createTopic


{
    "topicid": 1,
    "title": "Java",
    "body": "Java is a programming language",
    "datepublished": "2021-01-01T00:00:00Z",
    "userid": 1,
}
