services:
  postgres:
    # must be one of the versions supported by Gcloud
    image: postgres:15.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-011991}
    ports:
      - 15432:5432
    restart: unless-stopped
  redis:
    image: redis:7
    ports:
      - 16379:6379
